Repository Software-Development-Practices/gradle-invaders, pull requests merged in 2021-12, with the labels that each got.

#28 Setb 52/subfeat monster color diversity
  src/main/java/entity/EnemyShip.java
  src/main/java/entity/EnemyShipFormation.java
  src/main/java/entity/Ship.java
Labels: enhancement, fix

#27 SETB-13/feat dying effect
  src/main/java/engine/Core.java
  src/main/java/engine/DrawManager.java
  src/main/java/entity/EnemyShip.java
  src/main/java/screen/GameScreen.java
  src/main/resources/graphics
Labels: enhancement

#29 Setb 17/feat display h pcolor
  src/main/java/engine/Core.java
  src/main/java/entity/EnemyShip.java
  src/main/java/entity/EnemyShipFormation.java
  src/main/java/entity/Ship.java
Labels: enhancement

#42 [hotfix][SETB-14] resolve sonarqube code smell
  src/main/java/entity/Ship.java
Labels: fix

#39 [add][SETB-21] add Game Summary
  .vscode/settings.json
  src/main/java/engine/Core.java
  src/main/java/engine/DrawManager.java
  src/main/java/screen/Screen.java
  src/main/java/screen/SummaryScreen.java
  src/main/java/screen/TitleScreen.java
  src/test/java/testSummaryPackage/SummaryTest.java
Labels: enhancement

#48 [hotfix][SETB-14] sound build error
  src/main/java/engine/Core.java
  src/main/java/engine/Sound.java
  src/main/java/entity/Ship.java
Labels: fix
